export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const SHOW_CART_DLG = "SHOW_CART_DLG";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const UPDATE_CART_PRODUCT_QUANTITY = "UPDATE_CART_PRODUCT_QUANTITY";
